### ISSUE TITLE
Are there any plans to develop a LB based on CPP language?

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/alternator-load-balancing#4]
As I see, you have now provided LB libraries in four languages. Are there any plans to develop a CPP language LB library?

**Comment by nyh** [comment]
Good question. We did the languages that we knew people were using. Are you using a C++ DynamoDB driver? Can you help us get started but telling us how you use this driver? Or even better, contribute a load balancer for the C++ load balancer? It should be fairly easy to do - all the other languages took less than a day of work each :-)

**Comment by psarna** [comment]
Preliminary analysis:

One way of achieving load balancing would be to decorate all request handlers (https://github.com/aws/aws-sdk-cpp/blob/48c3e1c675745b9baf9dde7f280b5e39fd2fb5bd/aws-cpp-sdk-dynamodb/include/aws/dynamodb/DynamoDBClient.h#L361-L3283) with a small wrapper:
 * Change the URI (m_uri field) by calling the OverrideEndpoint() helper function
 * Call the original function, which will send to the overridden URI
It would, however, be quite cumbersome, since every single request handler would need to be changed. Instead, it looks like it should be enough if we:
 * Create a new class, inheriting from DynamoDBClient
 * Override its `BuildHttpRequest` function, which thankfully is virtual. Each request goes through this function, so it looks like it can be used to intercept every request and overwrite its target address. If I'm right, overriding this single function should be enough to provide load balancing similar to what other languages have. Of course, there should also be a thread which regularly updates the node list from alternator's /nodelist endpoint.

**Comment by psarna** [comment]
And indeed, here's a "AlternatorClient.h" snippet which successfully intercepts and rewrites URI of a request, tested with official DynamoDB examples from aws-doc-sdk-examples:
```cpp
#include <aws/core/Aws.h>
#include <aws/dynamodb/DynamoDBClient.h>

class AlternatorClient : public Aws::DynamoDB::DynamoDBClient {
public:
        AlternatorClient(const Aws::Client::ClientConfiguration &clientConfiguration = Aws::Client::ClientConfiguration())
                : Aws::DynamoDB::DynamoDBClient(clientConfiguration) {}
        virtual void BuildHttpRequest(const Aws::AmazonWebServiceRequest &request, const std::shared_ptr< Aws::Http::HttpRequest > &httpRequest) const override {
                httpRequest->GetUri() = Aws::Http::URI("http://localhost:8000");
                std::cout << "URI set to " << httpRequest->GetUri().GetURIString() << std::endl;
                return Aws::DynamoDB::DynamoDBClient::BuildHttpRequest(request, httpRequest);
        }
};
```
So the matter boils down to implementing a simple fetcher for local nodes and using the list to balance the load.
